sudo: required
dist: trusty

install:
  - conan --version
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - mkdir build && cd build
  - conan install .. --build=missing
  - source activate.sh
  - cmake --version

script:
#  - mkdir build && cd build
  - cmake ..
  - cmake --build .

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - CC=gcc-4.9
        - CXX=g++-4.9
      before_install:
        - sudo pip install --upgrade pip
        - sudo pip install --upgrade virtualenv
        # --ignore-installed (https://github.com/HelikarLab/candis/pull/36)
        - sudo pip install conan --ignore-installed
