build:

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan # It install conan too
  - conan install --build=missing -s compiler="Visual Studio" -s compiler.version=%TOOLCHAIN_VERSION%

build_script:
  - mkdir build && cd build
  - qmake ../mytetra.pro
  - nmake

environment:
  PYTHON: "C:\\Python27"
  PYTHON_VERSION: "2.7.8"
  PYTHON_ARCH: "32"
  matrix:
    - TOOLCHAIN_VERSION: 14
    - TOOLCHAIN_VERSION: 12
    - TOOLCHAIN_VERSION: 10